# -*- coding: utf-8 -*-
"""desafio14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HyjZYN5MJVnkoVDCN5r03UYZ1t2iH7fu
"""

import polars as pl

diamonds = pl.read_csv("https://me315-unicamp.github.io/dados/diamonds.csv.gz")
print(diamonds)

diamonds = diamonds.with_columns(
    pl.col("cut").cast(pl.Enum(["Fair", "Good", "Very Good", "Premium", "Ideal"])),
    pl.col("color").cast(pl.Enum(["J", "I", "H", "G", "F", "E", "D"])),
    pl.col("clarity").cast(pl.Enum(["I1", "SI2", "SI1", "VS2", "VS1", "VVS2", "VVS1", "IF"])),
)
print(diamonds)

from plotnine import ggplot, aes, geom_point, labs, theme_bw, facet_wrap, facet_grid

(
    ggplot(diamonds, aes(x="carat", y="price")) +
    geom_point(alpha = 0.05, colour = "red") +
    labs(title="Preço vs Peso", x = "peso", y = "preço") +
    theme_bw()
)  # o grafico de pontos cria uma melhor visualização e foi aplicada a função de transparencia pois o conjunto de dados é grande e os valores se sobrepoem.

(
    ggplot(diamonds, aes(x="carat", y="price")) +
    geom_point(alpha = 0.05) +
    facet_wrap("cut") +
    labs(title="Preço vs Peso", x = "peso", y = "preço") +
    theme_bw()
) # não, para comparar de forma mais eficiente foi usado a tecnica de facetamento, com isso temos um grafico para cada nível.
#Nos cortes de menor qualidade, como "Fair" e "Good", a linha de regressão cobre uma área de pontos muito mais dispersa,
#indicando uma maior variabilidade no preço para um dado peso. Em contraste, nos cortes de alta qualidade ("Premium" e "Ideal"), a relação entre
#carat e price é mais coesa e preditiva, com os pontos se agrupando de forma mais firme ao redor da linha de tendência.

(
    ggplot(diamonds, aes(x="carat", y="price", colour= "color", shape= "clarity")) +
    geom_point(alpha = 0.05) +
    facet_wrap("cut") +
    labs(title="Preço vs Peso", x = "peso", y = "preço") +
    theme_bw()
)

(
    ggplot(diamonds, aes(x="carat", y="price", colour= "color")) +
    geom_line() +
    facet_grid(rows="cut", cols= "clarity") +
    labs(title="Preço vs Peso", x = "peso", y = "preço", colour = "clareza") +
    theme_bw()
) # a dificuldade é o numero de combinações possiveis dadas as variaveis, por ser grande os pontos precisa de mais transparencia para conseguirmos diferencia-los
 # A associação positiva (quanto maior o peso, maior o preço) é universalmente forte em todos os painéis, confirmando que o carat é o fator dominante.
 # No entanto, o preço de referência e a variabilidade dessa relação mudam drasticamente
 # A medida que a clareza e a cor melhoram o piso de preço para um determinado peso aumenta.
 # A maior diferença é a densidade e o peso máximo nos painéis. Diamantes de muito alto carat são raros ou inexistentes nas combinações
 # de menor clareza e cor, enquanto essas categorias de alto peso se concentram nas combinações de qualidade superior.